theme: jekyll-theme-cayman

title: D'accord
description: D'accord - Adaptive Datenschutz-Cockpits in digitalen Ökosystemen
use_breadcrumbs: true

plugins:
  - jemoji

navigation:
  - name: "Home"
    link: "/Daccord"
    icon: "/Daccord/assets/images/house-solid.svg"
  - name: "Einleitung"
    link: "Einleitung"
    icon: "/Daccord/assets/images/bolt.svg"
  - name: "Anforderungen"
    link: "Anforderungen"
    icon: "/Daccord/assets/images/list-check.svg"
  - name: "Realisierung"
    link: "Realisierung"
    icon: "/Daccord/assets/images/gears.svg"
  - name: "Bewertung"
    link: "Bewertung"
    icon: "/Daccord/assets/images/user-doctor.svg"
  - name: "Systemeinführung"
    link: "Systemeinf%C3%BChrung"
    icon: "/Daccord/assets/images/play.svg"
  - name: "Lesestoff"
    link: "Lesestoff"
    icon: "/Daccord/assets/images/document.svg"